version: '3.9'

services:
  frontend:
    image: mokchhedul/branchfrontend:latest
    container_name: frontend
    ports:
      - "3000:80"  
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URI=http://3.85.87.207:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: mokchhedul/branchbackend:latest
    container_name: backend
    ports:
      - "5000:5000"  
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/crud
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
