# ArgoCD ingress application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mdmokchhedulislam/end-to-end-devops.git'
    targetRevision: develop
    path: k8s/ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
